### ISSUE TITLE
Issues due to definition of `index`

### ISSUE THREAD

**Issue by mgirlich** [RobinHankin/Brobdingnag#20]
For quite some time people had issues with loading `dbplyr`. After some investigation I boiled it down to this package.

The problem seems to be that `index` is defined as a [Union](https://github.com/RobinHankin/Brobdingnag/blob/master/R/aaa_allclasses.R)
(like in `Matrix`)

```r
setClassUnion("index", members =  c("numeric", "logical", "character"))
```

See also the https://github.com/tidyverse/dbplyr/issues/779.
@RobinHankin Maybe you can help with this issue.

**Comment by mgirlich** [comment]
It seems that importing `index` from `Matrix` fixes the problem.

```r
#' @importClassesFrom Matrix index
```

Would that be an option for you?

**Comment by RobinHankin** [comment]
fixed in ea9722f

**Comment by mgirlich** [comment]
Thanks a lot for fixing the issue so quickly!

**Comment by RobinHankin** [comment]
Reopening:

https://github.com/RobinHankin/disordR/issues/38
