### ISSUE TITLE
NAs in positive should not be allowed

### ISSUE THREAD

**Issue by martinmodrak** [RobinHankin/Brobdingnag#26]
Hi, 
not sure if this is actively maintained or not, but reporting an issue, at least for future users having the same problem.

It turns out you can create brobs with NA in the `positive` field. Those will be happily created, but cause errors when converting to numeric or some computations:

```r
b_na <- new("brob", x = c(30,10,15), positive = c(NA,TRUE, NA))
as.numeric(b_na)
# Error in out[!from@positive] <- -out[!from@positive] : 
#  NAs are not allowed in subscripted assignments

b_normal <- new("brob", x = c(5,5,5), positive = rep(TRUE,3))
b_na / b_normal
# No eror, but weird output
# [1] NAexp(25) +exp(5)   NAexp(10)

b_na + b_normal
# Error in out.x[ss] <- pmax(x1[ss], x2[ss]) + log1p(+exp(-abs(x1[ss] -  : 
#  NAs are not allowed in subscripted assignments
```

Thanks for all the hard work on the package!

**Comment by martinmodrak** [comment]
Related: https://github.com/quentingronau/bridgesampling/issues/21

**Comment by RobinHankin** [comment]
thanks for this, martinmodrak!  Will fix it up right now; leaving open until `revdepcheck()` comes back clean [which might be some time].

best wishes,

Robin

**Comment by martinmodrak** [comment]
So I investigated a bit more and now I know, where the NA in signs come from - here is a code that triggers the behaviour:

```
as.numeric(new("brob", x = 2, positive = TRUE)^(rep(NA, 2)))
```

(the exponent being a vector is necessary to trigger the behaviour)

Because at https://github.com/RobinHankin/Brobdingnag/blob/c9082b9689bc2b3680d17df98c25955092d346c0/R/brob.R#L224 there is no check for NAs

Overall it might be in fact more sensible (and break less existing code) to not throw an error, but instead `NA` any elements with `NA` in `positive` (and then keep the `positive` free of NAs)... But that's just like my opinion :-)

**Comment by RobinHankin** [comment]
will close now (observing in passing that the fix did indeed break another package, see 
 https://github.com/RobinHankin/untb/commit/fdd9b5bc99dc2dc3ae79877934b85755e249a9ef).
